### ISSUE TITLE
Cooldown list 

### ISSUE THREAD

**Issue by orihuu** [FoxxieBot/Foxxie#114]
A command listing all of the current cooldowns you have ex. reputation and daily, if you have no cooldown time left, it would say so. otherwise just the time left until the cooldown is over.

**Comment by Ruffpuff1** [comment]
Ok I think I'll work on this now.

**Comment by Ruffpuff1** [comment]
Added in https://github.com/FoxxieBot/Foxxie/commit/70203b267dd36c036fd1f867e93250ea6dd86d72
